# Generated by Django 4.2.5 on 2023-10-06 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_remove_comment_listing_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="commenters",),
        migrations.AddField(
            model_name="comment",
            name="commenter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="User",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing",
                to="auctions.listing",
            ),
        ),
    ]
