# Generated by Django 4.2.5 on 2023-10-09 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_remove_comment_commenters_comment_commenter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid_listing",
                to="auctions.listing",
            ),
        ),
    ]
