# Generated by Django 4.2.5 on 2023-10-09 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_bid_listing"),
    ]

    operations = [
        migrations.RemoveField(model_name="bid", name="amount",),
        migrations.RemoveField(model_name="bid", name="listing",),
        migrations.AddField(
            model_name="bid", name="bid_amount", field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="bid",
            name="bid_listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.listing",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="amount",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auctions.bid"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
