# Generated by Django 4.2.5 on 2023-10-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auctions",
            "0009_remove_bid_amount_remove_bid_listing_bid_bid_amount_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="bid_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name="listing",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
    ]
