# Generated by Django 4.2.5 on 2023-10-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_alter_bid_bid_amount_alter_listing_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="bid_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=11
            ),
        ),
    ]
